### ISSUE TITLE
Preview Fails in ST 3

### ISSUE THREAD

**Issue by gooddadmike** [michfield/sublime-strapdown-preview#10]
When I install with the package manager and hit preview, nothing comes up. When I chose preview in Sublime Text the <script> file points to 

```
`<script src="///C:/Users/mike/AppData/Roaming/Sublime%20Text%203/Installed%20Packages/Strapdown%20Markdown%20Preview.sublime-package/strapdown/strapdown.js"></script>
```

When I check that location Strapdown%20Markdown%20Preview.sublime-package points to a file. How could this direct the browser to strapdown.js? Is it supposed to be a folder reference? Is there a settings file where I can change this?

**Comment by WillChilds-Klein** [comment]
I'm getting the same error upon attempting to preview in browser. my console spits out:

````
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "Strapdown Markdown Preview in /Users/will/Library/Application Support/Sublime Text 3/Installed Packages/Strapdown Markdown Preview.sublime-package", line 101, in run
AttributeError: 'module' object has no attribute 'open'
````

this is the only feature which I require from this plugin (which I think is a great idea!), so I was wondering, what are the chances of a fix on this?

**Comment by thomscode** [comment]
Will,
 I have not seen any updates to this code or issue in several months. I don't have much hope that it will be fixed in the Package control version. However, if you download the code and manually add the package to Sublime, it has been working for me.

Hope that helps,
Thom

**Comment by WillChilds-Klein** [comment]
I see, I'll try that. thanks @thomscode !
